alertmanager:
  enabled: false
grafana:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
prometheusOperator:
  enabled: true
prometheus:
  enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-db
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi